---
# tasks file for dhcpd

- name: Installing DHCP (Ubuntu)
  apt:
   name:
     - dhcp
   state: latest
   update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Installing DHCP (CentOS)
  dnf:
   name: 
     - dhcp
   state: latest
   update_cache: yes
  when: ansible_distribution == "CentOS"
