---
# tasks file for mariadb
- name: Install MariaDB Package in Ubuntu
  apt:
    name:
      - mariadb-server
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install MariaDB Package in Centos
  apt:
    name:
      - mariadb-server
    state: latest
    update_cache: yes
  when: ansible_distribution == "Centos"
