---
# tasks file for bind9
- name: Install bind for Ubuntu
  package:
    name: bind9
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install bind for CentOS
  package:
    name: bind
    state: latest
  when: ansible_distribution == "CentOS"


- name: Set hostname
  hostname:
    name: Group8

#sample
